-- Seed the colleges table with the official ACPDC diploma admission college list
-- (Gujarat, 115 colleges, grouped by zone in source; stored with district as city).
-- Run this in the Supabase SQL Editor.
--
-- Idempotent: each college is inserted only if no row with the same name
-- (case-insensitive) already exists, so re-running is safe and any colleges
-- you already added manually are left untouched.

INSERT INTO colleges (name, city)
SELECT v.name, v.city
FROM (VALUES
    -- Central Zone
    ('Government Polytechnic for Girls, Ahmedabad', 'Ahmedabad'),
    ('Government MCA College, Maninagar', 'Ahmedabad'),
    ('R. C. Technical Institute, Ahmedabad', 'Ahmedabad'),
    ('Government Polytechnic, Ahmedabad', 'Ahmedabad'),
    ('Alpha College of Engg. & Technology, Kalol', 'Ahmedabad'),
    ('Swami Krishanjivandasji Insti of Tech', 'Ahmedabad'),
    ('L. J. Polytechnic, Ahmedabad', 'Ahmedabad'),
    ('School of Engineering and Applied Sciences, Rai University', 'Ahmedabad'),
    ('Swarrnim Institute of Technology', 'Ahmedabad'),
    ('Aditya Silver Oak University of Technology', 'Ahmedabad'),
    ('Government Polytechnic, Gandhinagar', 'Gandhinagar'),
    ('Excel Institute of Diploma Studies, Kalol', 'Gandhinagar'),
    ('Atul Polytechnic, Khadat', 'Gandhinagar'),
    ('V.P.M.P. Polytechnic, Gandhinagar', 'Gandhinagar'),
    ('Shankarsinh Vaghela Bapu Institute of Technology', 'Gandhinagar'),
    ('Shree Swaminarayan Polytechnic, Gandhinagar', 'Gandhinagar'),
    ('Swaminarayan College of Engineering & Technology', 'Gandhinagar'),
    ('Navsarjan School of Technology', 'Gandhinagar'),
    ('Shri J.M.Sabva Institute of Engg. & Technology', 'Botad'),
    ('Shri N. M. Gopani Polytechnic Institute, Ranpur', 'Botad'),
    ('Government Polytechnic, Mahemdavad', 'Kheda'),
    ('D. A. Diploma Engg. and Technology, Mahemdavad', 'Kheda'),
    ('R.H.Patel Insti. of Technology, Goblaj', 'Kheda'),
    ('Dalia Insti. of Diploma Studies, Kanera', 'Kheda'),
    ('Image Engg. and Technical Institute, Kheda', 'Kheda'),
    -- East Central Zone
    ('H. B. Patel Institute of Diploma Engg. & Tech., Limbodara', 'Mahisagar'),
    ('B and B Institute of Technology, V V Nagar', 'Anand'),
    ('Ipcowala Institute of Engg. & Technology, Petlad', 'Anand'),
    ('Government Polytechnic, Chhota Udepur', 'Chhota Udepur'),
    ('Government Polytechnic, Dahod', 'Dahod'),
    ('Polytechnic, M. S. University, Vadodara', 'Vadodara'),
    ('Parul Polytechnic Institute, Vadodara', 'Vadodara'),
    ('S.B. Polytechnic, Savli', 'Vadodara'),
    ('RMS Polytechnic, Vadodara', 'Vadodara'),
    ('Butler Polytechnic, Vadodara', 'Vadodara'),
    ('Parul Institute of Engg. and Technology (DS), Vadodara', 'Vadodara'),
    ('Sigma Institute of Technology & Engg. (Polytechnic), Vadodara', 'Vadodara'),
    ('Faculty of Diploma Engineering (Neotech Education), Vadodara', 'Vadodara'),
    ('Government Polytechnic, Halol', 'Panchmahal'),
    ('Government Polytechnic, Godhra', 'Panchmahal'),
    -- North Zone
    ('Government Polytechnic, Palanpur', 'Banaskantha'),
    ('Government Polytechnic, Vadnagar', 'Mehsana'),
    ('M.L.Institute of Diploma Studies, Bhandu', 'Mehsana'),
    ('Shree Hari Polytechnic Institute, Kadi', 'Mehsana'),
    ('Navsarjan Polytechnic, Kuwaida', 'Mehsana'),
    ('B.S.Patel Polytechnic, Kherva', 'Mehsana'),
    ('Swami Sacchidanand Polytechnic College, Visnagar', 'Mehsana'),
    ('Shree Vasudevbhai & Kantibhai Patel Institute of Engineering, Kadi', 'Mehsana'),
    ('Dr. Natubhai P. Patel Polytechnic, Jotana', 'Mehsana'),
    ('S. P. B. Engineering College (Diploma Courses)', 'Mehsana'),
    ('Shri Satsangi Sakeddham "Ram Ashram" Group of Institutions', 'Mehsana'),
    ('Merchant Institute of Diploma Studies, Piludara', 'Mehsana'),
    ('K. D. Polytechnic, Patan', 'Patan'),
    ('M.K.Institute of Diploma Studies and Technological Research, Patan', 'Patan'),
    ('Smt. R.S.Patel Insti. of Diploma Engg., Shelavi, Patan', 'Patan'),
    ('Tatva Institute of Technological Studies, Modasa', 'Aravalli'),
    ('Government Engineering College, Modasa', 'Aravalli'),
    ('Government Polytechnic, Himmatnagar', 'Sabarkantha'),
    ('Ved Vyas Polytechnic, Himmatnagar', 'Sabarkantha'),
    ('Grow More Faculty of Diploma Engg., Himmatnagar', 'Sabarkantha'),
    ('Arrdekta Institute of Technology, Khedbrahma', 'Sabarkantha'),
    ('Asian Institute of Technology, Vadali', 'Sabarkantha'),
    -- Saurashtra Zone
    ('Government Polytechnic, Bhuj', 'Kutch'),
    ('T.F.Gandhidham Polytechnic, Adipur', 'Kutch'),
    ('Veerayatan Institute of Engg, Mandvi', 'Kutch'),
    ('HJD Inst. of Technical Education & Research, Kera', 'Kutch'),
    ('A.V.Parekh Technical Institute, Rajkot', 'Rajkot'),
    ('Government Polytechnic, Rajkot', 'Rajkot'),
    ('Sanjaybhai Rajguru College of Diploma Engg, Rajkot', 'Rajkot'),
    ('Asiatic Institute of Science & Technology, Gondal', 'Rajkot'),
    ('Christ Polytechnic Institute, Rajkot', 'Rajkot'),
    ('Atmiya Institute of Technology, Rajkot', 'Rajkot'),
    ('R K University School of Diploma Studies, Rajkot', 'Rajkot'),
    ('Darshan Inst. of Eng. & Tech. for Diploma Studies, Rajkot', 'Rajkot'),
    ('Radhe Institute of Engineering & Technology, Upleta', 'Rajkot'),
    ('Marwadi Education Foundation, Rajkot', 'Rajkot'),
    ('Shri Labhubhai Trivedi Institute of Engineering and Technology, Rajkot', 'Rajkot'),
    ('Lakhdhirji Engg. College, Morbi', 'Morbi'),
    ('C.U.Shah Government Polytechnic, Surendranagar', 'Surendranagar'),
    ('C.U.Shah Technical Institute of Diploma Studies, Wadhwan', 'Surendranagar'),
    -- South Zone
    ('Shri K.J.Polytechnic, Bharuch', 'Bharuch'),
    ('Valia Polytechnic College, Bharuch', 'Bharuch'),
    ('Sigma Engineering College, Matar', 'Bharuch'),
    ('Government Polytechnic, Waghai', 'Dang'),
    ('Government Polytechnic, Navsari', 'Navsari'),
    ('Vallabhbudhi Polytechnic, Navsari', 'Navsari'),
    ('Prime College of Diploma, Mangrol', 'Navsari'),
    ('N. G. Patel Polytechnic, Isroli', 'Surat'),
    ('Government Polytechnic, Vyara', 'Surat'),
    ('Government Polytechnic for Girls, Surat', 'Surat'),
    ('Dr. S. & S.S.Gandhi College of Engg. and Technology, Surat', 'Surat'),
    ('Bhulabhai Vanmalibhai Patel Inst. of Tech. (DS), Umrakh', 'Surat'),
    ('Vidhyadeep Institute of Engg & Technology, Kim', 'Surat'),
    ('Bhagwan Mahavir Polytechnic, Surat', 'Surat'),
    ('A Y Dadabhai Technical Institute, Kosamba', 'Surat'),
    ('Tapi Diploma Engineering College, Surat', 'Surat'),
    ('Chhotubhai Gopalbhai Patel Institute of Technology, Bardoli', 'Surat'),
    ('Shree Dhanvantray College of Diploma Engg., Kim', 'Surat'),
    ('Government Polytechnic, Valsad', 'Valsad'),
    ('Laxmi Institute of Technology, Sarigam', 'Valsad'),
    -- West Coastal Zone
    ('Dr.J.N.Maheta Government Polytechnic, Amreli', 'Amreli'),
    ('Arun Muchhala Engineering College, Dhari', 'Amreli'),
    ('GMB Polytechnic, Rajula', 'Amreli'),
    ('Sir Bhavsinhji Polytechnic Institute, Bhavnagar', 'Bhavnagar'),
    ('Bhavnagar Polytechnic, Todi', 'Bhavnagar'),
    ('Government Polytechnic, Jamnagar', 'Jamnagar'),
    ('Kalyan Polytechnic, Jamnagar', 'Jamnagar'),
    ('Government Polytechnic, Junagadh', 'Junagadh'),
    ('Amrut Institute, Junagadh', 'Junagadh'),
    ('Noble Group of Institutions, Junagadh', 'Junagadh'),
    ('N.R.Vekaria Insti. of Technology, Junagadh', 'Junagadh'),
    ('Om Insti. of Engg. & Technology, Junagadh', 'Junagadh'),
    ('Balaji Insti. of Eng. & Tech, Junagadh', 'Junagadh'),
    ('Dr. Subhash Technical Campus, Junagadh', 'Junagadh'),
    ('Government Polytechnic, Porbandar', 'Porbandar')
) AS v(name, city)
WHERE NOT EXISTS (
    SELECT 1 FROM colleges c WHERE lower(c.name) = lower(v.name)
);
